### ISSUE TITLE
Delo v CoCalcu

### ISSUE THREAD

**Issue by izazupan** [CebuljIza/Shortest-matching#1]
Dodali sva datoteko 2022-12-22-100842.ipnyb, kjer sva začeli z delom na grafih. Našli sva načine, kako izbrati točke v kvadratu, krogu in trikotniku, jih dodati v graf in povezati. Napisali sva tudi algoritem, ki najde prirejanje, vendar pa ta algoritem cen povezav ne upošteva, zato ne najde najcenejšega prirejanja, tu pa se nama zatakne, ker nisva prepričani, kako bi to popravili. Algoritem bi nato želeli še popraviti, da ne izpiše samo parov, ki so v prirejanju, ampak tudi te povezave označi na grafu, poleg tega pa tudi sešteje cene povezav v prirejanju. (Več najinih komentarjev in težav pa je napisanih čisto spodaj v datoteki.)

**Comment by izazupan** [comment]
Sedaj sva datoteko (CLP.ipnyb) popravili tako, da algoritem ustvari grafe in vrne najmanjšo vsoto razdalj (najmanjše prirejanje).
Trenutno naju predvsem zanima, kako bi te grafe narisali - mogoče kar s funkcijo G.plot(edge_labels=True), vendar to vrne samo graf z vsemi povezavami, ne pa tudi označenih povezav, ki so v prirejanju. Ali obstaja še kakšen drug program oz. programski jezik, ki ga raje uporabiva za prikaz grafov?

**Comment by jaanos** [comment]
Najprej bi opozoril na to, kako generirata točke. Kot vidim, že v štartu podatke zaokrožujeta - tega ne počnita s podatki, s katerimi bosta še računali (to je smiselno početi le za izpisovanje). Da bodo točke že vektorji, s katerimi lahko potem naprej računata (ne da bi jih bilo potrebno vsakič pretvarjati), lahko točke v enotskem kvadratu generirata enostavno kot
```sage
V = RDF^2 # vektorski prostor R^2
tocke = [V.random_element(min=0, max=1) for _ in range(2*n)]
```
Mimogrede, metodi za generiranje točk v krogu in trikotniku nista ustrezni - pri obeh bodo namreč točke gosteje posejane, ko se oddaljujeta od osi *y*. Za generiranje točk v enotskem krogu generirajta točke enakomerno naključno v [-1, 1] × [-1, 1] (podobno kot zgoraj), a ohranita le točke z normo največ 1 (uporabita zanko `while`, da polnita seznam, dokler nimata dovolj točk). Podoben pristop bi deloval tudi za trikotnik, a bo bolj učinkovito tako:
1. generirata točke v enotskem kvadratu,
2. točke nad premico *x* + *y* = 1 preslikata pod to premico,
3. točke z linearno preslikavo preslikata v enakostranični trikotnik.

Nekako tako bi šlo:
```sage
V = RDF^2
A = Matrix([[1, 1/2], [0, sqrt(3)/2]]) # linearna preslikava
b = V([1/2, sqrt(3)/6]) # premik, da bo središče trikotnika v izhodišču
ee = V([1, 1]) # vektor za preslikovanje pod x+y = 1
tocke = [A*(v if sum(v) < 1 else ee-v) - b for _ in range(2*n) for v in [V.random_element(min=0, max=1)]]
```

V samem grafu `G` bo bolje, če so imena točk kar indeksi v seznamu `tocke` - lahko uporabita kar vgrajene polne grafe ter določita uteži povezav:
```sage
G = graphs.CompleteGraph(len(tocke))
G.set_pos({i: v for i, v in enumerate(tocke)}) # položaji točk pri izrisovanju
for u, v in G.edges(labels=False):
    G.set_edge_label(u, v, (tocke[u] - tocke[v]).norm())
```
Oznake (uteži) so sedaj nezaokrožene razdalje - za potrebe izrisovanja lahko določita še pomožen graf `H` z zaokroženimi oznakami:
```sage
H = Graph([(*e, N(w, digits=2)) for *e, w in G.edges(labels=True)])
H.set_pos(G.get_pos())
H.plot(edge_labels=True)
```

Sedaj bo treba v CLP upoštevati oznake (uteži) povezav v grafu `G` - vsoto uteži izbranih povezav želimo seveda minimizirati.
```sage
p = MixedIntegerLinearProgram(maximization=False)
b = p.new_variable(binary=True)
p.set_objective(sum([w * b[Set(e)] for *e, w in G.edges(labels=True)])) # upoštevamo uteži povezav

for v in G: # tukaj nas uteži ne zanimajo
    p.add_constraint(sum([b[Set(e)] for e in G.edges_incident(v, labels=False)]) == 1)

cena = p.solve() # vrne vrednost ciljne funkcije
b = p.get_values(b)

M = [tuple(e) for e, i in b.items() if i]
print(M)
```
Sedaj lahko s pomočjo grafa `H` (tj., da se izpišejo zaokrožene razdalje) predstavita prirejanje `M`, npr.:
```sage
H.subgraph(edges=M).plot(edge_labels=True) # podgraf H s povezavami iz prirejanja
H.plot(edge_colors={"red": M}) # graf H z rdeče pobarvanimi povezavami iz prirejanja
```

Vidim, da sta kodo organizirali v ustrezne funkcije - morda bi svetoval, da ločita samo generiranje točk od funkcije, ki vrne grafa `G` in `H` za podane točke. Svetujem tudi, da si funkcija za poganjanje rezultate sproti zapisuje v datoteko - lahko uporabita npr. vgrajeni modul `csv`. Seveda bo potem treba dodati še ustrezne funkcije za dvobarvna prirejanja (grafe lahko zgradita iz `graphs.CompleteBipartiteGraph(n, n)`).

**Comment by BarbaraPal** [comment]
Kodo v datoteki CLP.ipnyb sve popravili in za majhne n že dobili podatke. Prosiva, če lahko poženete še za večje n (koda za to je napisana na dnu datoteke CLP.ipnyb).

**Comment by izazupan** [comment]
Pozdravljeni, najprej hvala za dosedanjo pomoč.
Ali mislite, da je potrebno, da bi za verodostojne podatke CLP mogli pognati več kot 50x, kot imava napisano v kodi? 
Za večje število ponovitev sta najina računalnika prepočasna, v kolikor pa menite, da je 50 ponovitev za izračun pričakovane vrednosti premalo, bi prosili, če lahko vse še enkrat poženete s 100 oz. 1000 (oz. kolikor jih je potrebno) ponovitvami.

**Comment by jaanos** [comment]
Načeloma lahko število ponovitev prilagajata časovni zahtevnosti - pri daljšem času izvajanja naredita manj ponovitev, seveda za ceno natančnosti. Glede na to, da je čas izvajanja pri 50 ponovitvah očitno že nezanemarljivo dolg, bi rekel, da bo to kar ustrezno število ponovitev.
